{{- if .Values.observe.cdc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "omnix.fullname" . }}-kafka-connect
  labels:
    {{- include "omnix.labels" . | nindent 4 }}
    component: observe-connect
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    component: observe-connect
  ports:
  - { name: rest, port: 8083, targetPort: rest }
{{- end }}
