# Compliance: P17 (no mutable default args in AXIOM modules).
"""Build a tamper-evident audit handoff zip (slice 18d step 3)."""

from __future__ import annotations

import hashlib
import json
import sys
import zipfile
from datetime import datetime, timezone
from pathlib import Path

from omnix.find_bugs.receipt_emitter import verify_scan_directory
from omnix.omnix_version import __version__ as OMNIX_VERSION

from .finding_receipt import compute_project_id, now_iso8601_utc


VAULT_README = """# OMNIX Compliance Vault — Audit Handoff

This archive contains cryptographically-signed evidence of code analysis
findings produced by OMNIX. Each finding is signed with Ed25519. Each scan
run is anchored by an ML-DSA-65 (post-quantum) signature over a Merkle tree
of finding hashes.

## Verifying

Install OMNIX: `pip install omnix` (≥0.5.0)

For each scan in `scans/`:

```
omnix axiom verify-scan scans/<scan_id>/ \\
  --ed25519-pubkey public_keys/ed25519_pubkey.pem \\
  --mldsa-pubkey public_keys/mldsa_pubkey.pem
```

Exit code 0 = verified. Exit code 1 = tampered.

## Trust assumptions

- Verification proves the receipt has not been altered since signing.
- Verification does NOT prove the underlying code analysis is correct or complete.
- An auditor should review scan_summary in each scan_manifest.json for context.

## Tampering detection

OMNIX detects three modes of tampering:
1. Modify a finding receipt → Merkle root mismatch
2. Delete a finding receipt → Missing finding
3. Modify the manifest → Invalid ML-DSA signature

## Questions

Contact your OMNIX operator for methodology questions.

Generated by OMNIX {omnix_version} on {generated_at}.
"""


def build_vault_zip(
    project_root: Path,
    out_path: Path | None,
    since_iso: str | None = None,
    include_tampered: bool = False,
) -> tuple[Path, int, int]:
    """Build vault zip. Returns ``(out_path, scans_included, scans_excluded)``."""
    project_root = project_root.resolve(strict=True)
    project_id = compute_project_id(project_root)
    receipts_root = Path.home() / ".omnix" / "receipts" / "findings" / project_id

    if not receipts_root.is_dir():
        raise FileNotFoundError(f"no scans found for project {project_id} at {receipts_root}")

    ed25519_pub = project_root / ".omnix" / "pubkey.pem"
    mldsa_pub = Path.home() / ".omnix" / "keys" / "public.pem"
    for p in (ed25519_pub, mldsa_pub):
        if not p.is_file():
            raise FileNotFoundError(f"public key missing: {p}")

    scan_dirs = sorted(
        (d for d in receipts_root.iterdir() if d.is_dir()),
        key=lambda d: d.name,
    )
    if not scan_dirs:
        raise FileNotFoundError(f"no scans found under {receipts_root}")

    if since_iso:
        filtered: list[Path] = []
        for sd in scan_dirs:
            mp = sd / "scan_manifest.json"
            if not mp.is_file():
                continue
            try:
                m = json.loads(mp.read_text(encoding="utf-8"))
                if str(m.get("scan_started_at") or "") >= since_iso:
                    filtered.append(sd)
            except (OSError, json.JSONDecodeError, UnicodeDecodeError):
                continue
        scan_dirs = filtered

    if not scan_dirs:
        raise FileNotFoundError(f"no scans matching --since {since_iso!r}")

    included: list[Path] = []
    excluded: list[tuple[Path, str]] = []
    for sd in scan_dirs:
        ok, reason = verify_scan_directory(sd, ed25519_pub, mldsa_pub)
        if ok or include_tampered:
            included.append(sd)
            if not ok:
                print(
                    f"WARN: including tampered scan {sd.name}: {reason}",
                    file=sys.stderr,
                )
        else:
            excluded.append((sd, reason))
            print(
                f"WARN: excluding tampered scan {sd.name}: {reason}",
                file=sys.stderr,
            )

    if not included:
        raise FileNotFoundError("no verifiable scans to include in vault")

    dest = out_path
    if dest is None:
        ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        dest = Path.cwd() / f"omnix-vault-{project_id}-{ts}.zip"
    dest = Path(dest).resolve()
    dest.parent.mkdir(parents=True, exist_ok=True)

    vault_index: dict[str, object] = {
        "project_id": project_id,
        "exported_at": now_iso8601_utc(),
        "omnix_version": OMNIX_VERSION,
        "scan_count": len(included),
        "scans": [],
    }

    scan_entries: list[dict[str, object]] = []
    with zipfile.ZipFile(dest, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(
            "public_keys/ed25519_pubkey.pem",
            ed25519_pub.read_bytes(),
        )
        zf.writestr("public_keys/mldsa_pubkey.pem", mldsa_pub.read_bytes())

        for sd in included:
            for f in sd.iterdir():
                if not f.is_file():
                    continue
                arcname = f"scans/{sd.name}/{f.name}".replace("\\", "/")
                zf.write(f, arcname=arcname)
            mp = sd / "scan_manifest.json"
            entry: dict[str, object] = {"scan_id": sd.name}
            if mp.is_file():
                raw_m = mp.read_bytes()
                entry["manifest_sha256"] = hashlib.sha256(raw_m).hexdigest()
                try:
                    m = json.loads(raw_m.decode("utf-8"))
                    entry["scan_started_at"] = m.get("scan_started_at")
                    entry["finding_count"] = m.get("finding_count")
                    entry["merkle_root"] = m.get("merkle_root")
                except (json.JSONDecodeError, UnicodeDecodeError):
                    pass
            scan_entries.append(entry)

        vault_index["scans"] = scan_entries
        exported_at = str(vault_index["exported_at"])
        zf.writestr(
            "vault_index.json",
            json.dumps(vault_index, indent=2, sort_keys=True),
        )
        zf.writestr(
            "README.md",
            VAULT_README.format(omnix_version=OMNIX_VERSION, generated_at=exported_at),
        )

    return dest, len(included), len(excluded)
