#!/usr/bin/env python3
"""Generate viewerEngine.ts from src/web/index.html (graph IIFE only)."""
from __future__ import annotations

import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
INDEX = REPO / "src" / "web" / "index.html"
OUT = (
    REPO
    / "src"
    / "studio"
    / "frontend"
    / "src"
    / "components"
    / "Graph"
    / "viewerEngine.ts"
)

START = 886  # 'use strict'
END = 6598  # closing `})();` of async boot (inclusive)


def main() -> None:
    lines = INDEX.read_text(encoding="utf-8").splitlines(keepends=True)
    body = lines[START - 1 : END]
    s = "".join(body)

    # 1) graph container -> studio mount
    s = s.replace(
        "    const host = document.getElementById('graph-container');",
        "    const host = studio._container;",
    )

    # 2) Pixi: store main ticker for destroy
    s = s.replace(
        "    app.ticker.add(() => {",
        "    const _omnixMainTicker = () => {",
    )
    tick_close = (
        "        }\n"
        "      }\n"
        "    });\n"
        "  }\n"
        "\n"
        "  let dragStart = null;"
    )
    tick_repl = (
        "        }\n"
        "      }\n"
        "    };\n"
        "    app.ticker.add(_omnixMainTicker);\n"
        "    studio._mainTicker = _omnixMainTicker;\n"
        "  }\n"
        "\n"
        "  let dragStart = null;"
    )
    if tick_close not in s:
        raise SystemExit("ticker end anchor not found")
    s = s.replace(tick_close, tick_repl, 1)

    # 3) Planet symbol: Studio — drill to Monaco; skip default symbol popup
    s = s.replace(
        "        e.stopPropagation();\n"
        "        showSymbolDetailPopup(sym, fileData);",
        "        e.stopPropagation();\n"
        "        if (\n"
        "          (sym.type === 'function' || sym.type === 'class' || sym.type === 'method') &&\n"
        "          typeof studio._options.onFunctionNodeClick === 'function' &&\n"
        "          sym &&\n"
        "          sym.id\n"
        "        ) {\n"
        "          try {\n"
        "            studio._options.onFunctionNodeClick(String(sym.id));\n"
        "          } catch (_e) { /* */ }\n"
        "          return;\n"
        "        }\n"
        "        showSymbolDetailPopup(sym, fileData);",
    )
    # 3b) Search zoom: same for zoomToRawNode hit
    s = s.replace(
        "        if (hit) showSymbolDetailPopup(hit, fileData);",
        "        if (hit) {\n"
        "          if (\n"
        "            (hit.type === 'function' || hit.type === 'class' || hit.type === 'method') &&\n"
        "            typeof studio._options.onFunctionNodeClick === 'function' &&\n"
        "            hit &&\n"
        "            hit.id\n"
        "          ) {\n"
        "            try {\n"
        "              studio._options.onFunctionNodeClick(String(hit.id));\n"
        "            } catch (_e) { /* */ }\n"
        "          } else {\n"
        "            showSymbolDetailPopup(hit, fileData);\n"
        "          }\n"
        "        }",
    )

    # 4) Star file: optional file path callback
    s = s.replace(
        "        e.stopPropagation();\n        hideSymbolPopup();\n        transitionToPlanet(fileData);",
        "        e.stopPropagation();\n        try {\n"
        "          if (typeof studio._options.onFileOrDirClick === 'function' && fileData && fileData.filePath) {\n"
        "            studio._options.onFileOrDirClick(String(fileData.filePath));\n"
        "          }\n"
        "        } catch (_e) { /* */ }\n"
        "        hideSymbolPopup();\n"
        "        transitionToPlanet(fileData);",
    )

    # 5) Remove sync boot: from /** --- Boot --- */ through end of async boot
    s, n = re.subn(
        r"\n  /\*+ --- Boot --- \*/\n"
        r"[\s\S]*?"
        r"\n  \(async function boot\(\) \{[\s\S]*?"
        r"\n  \}\)\(\);",
        _BOOT_REPLACEMENT,
        s,
        count=1,
    )
    if n != 1:
        raise SystemExit("Failed to match Boot section + async IIFE")

    header = (
        "// @ts-nocheck\n"
        "// AUTO-GENERATED by scripts/build_studio_viewer_engine.py — do not hand-edit\n"
        'import * as PIXI from "pixi.js";\n'
        'import * as d3 from "d3";\n'
        'import { gsap } from "gsap";\n\n'
        "export function installOmnixViewerEngine(studio) {\n"
    )
    footer = "\n}\n"

    OUT.write_text(header + s + footer, encoding="utf-8")
    print(f"Wrote {OUT} ({OUT.stat().st_size} bytes)")


_BOOT_REPLACEMENT = r"""
  /** --- Boot (Studio) --- */
  function __omnixWireOptionalDom() {
    const g = (id) => document.getElementById(id);
    const el = (id) => g(id);
    if (el('entrance')) el('entrance').addEventListener('click', skipEntrance);
    if (el('btn-fullscreen')) {
      el('btn-fullscreen').addEventListener('click', () => {
        if (!document.fullscreenElement) document.documentElement.requestFullscreen?.();
        else document.exitFullscreen?.();
      });
    }
    if (el('btn-dark-matter')) {
      el('btn-dark-matter').addEventListener('click', () => {
        darkMatterVisible = !darkMatterVisible;
        const b = el('btn-dark-matter');
        if (b) {
          b.style.opacity = darkMatterVisible ? '1' : '0.5';
          b.style.borderColor = darkMatterVisible ? '#8b5cf6' : 'rgba(99,102,241,0.2)';
        }
      });
    }
    if (el('btn-timeline')) {
      el('btn-timeline').addEventListener('click', () => {
        timelineVisible = !timelineVisible;
        const pan = el('timeline-panel');
        if (pan) pan.style.display = timelineVisible ? 'block' : 'none';
        const b = el('btn-timeline');
        if (b) {
          b.style.opacity = timelineVisible ? '1' : '0.5';
          b.style.borderColor = timelineVisible ? '#a855f7' : 'rgba(99,102,241,0.2)';
        }
        if (timelineVisible) {
          const s = el('timeline-slider');
          if (s) applyTimelineSnapshot(parseInt(s.value, 10) || 0);
        } else {
          for (let i = 0; i < simNodes.length; i++) {
            delete simNodes[i]._timelineScale;
            delete simNodes[i]._timelineAlpha;
          }
          syncPixiFromSim();
        }
      });
    }
    if (el('timeline-slider')) {
      el('timeline-slider').addEventListener('input', (e) => {
        const idx = parseInt(e.target.value, 10);
        applyTimelineSnapshot(idx);
      });
    }
    if (el('btn-export')) {
      el('btn-export').addEventListener('click', async () => {
        if (!GRAPH_API_URL) {
          alert('Export needs the OMNIX server URL.');
          return;
        }
        try {
          const r = await fetch(GRAPH_API_URL, { cache: 'no-store' });
          if (!r.ok) {
            alert('Export failed: HTTP ' + r.status);
            return;
          }
          const j = await r.json();
          const blob = new Blob([JSON.stringify(j, null, 2)], { type: 'application/json' });
          const a = document.createElement('a');
          a.href = URL.createObjectURL(blob);
          a.download = 'graph.json';
          a.click();
          URL.revokeObjectURL(a.href);
        } catch (e) {
          alert('Export failed');
        }
      });
    }
    if (el('search-input')) {
      el('search-input').addEventListener('input', () => {
        clearTimeout(searchDebounceTimer);
        searchDebounceTimer = setTimeout(() => {
          const si = el('search-input');
          searchQuery = (si && si.value && si.value.trim()) || '';
          runSearchIndex();
        }, SEARCH_DEBOUNCE_MS);
      });
      el('search-input').addEventListener('keydown', (ev) => {
        if (ev.key === 'Enter' && searchMatches.length) zoomToRawNode(searchMatches[0]);
      });
    }
    if (el('xray-close')) el('xray-close').addEventListener('click', closeXray);
  }

  function __omnixKeydownHandler(ev) {
    if (ev.key === 'Enter' && document.activeElement && document.activeElement.id === 'ai-question-input') {
      const dirId = xrayDirId || '';
      void runAIAsk(dirId);
      return;
    }
    if (ev.key === 'Escape') {
      hideSymbolPopup();
      if (xrayOpen) {
        closeXray();
        return;
      }
      if (viewLevel === 'planet' || viewLevel === 'star') {
        goBack();
        return;
      }
      if (viewLevel === 'galaxy' && selectedDir) {
        selectedDir = null;
        killTweens();
        gsap.set(layerEdges, { alpha: 1 });
        nodePool.forEach((p) => {
          if (!p.container) return;
          gsap.killTweensOf(p.container);
          gsap.killTweensOf(p.container.scale);
          p.container.alpha = searchQuery && p.simNode && !nodeMatchesSearch(p.simNode) ? 0.25 : 1;
        });
        syncPixiFromSim();
        updateBreadcrumb();
        if (typeof studio._options.onDeselect === 'function') {
          try {
            studio._options.onDeselect();
          } catch (_e) { /* */ }
        }
        return;
      }
      killTweens();
      resetGalaxyDrillState();
      fitWorldToNodes();
      updateBreadcrumb();
    }
  }

  function __omnixResizeHandler() {
    resizePixi();
  }

  __omnixWireOptionalDom();
  window.addEventListener('keydown', __omnixKeydownHandler);
  window.addEventListener('resize', __omnixResizeHandler);

  studio._loadGraphFromData = function (data) {
    if (!data || !Array.isArray(data.nodes) || !Array.isArray(data.links)) {
      showLoadError('Invalid graph payload (expected nodes + links arrays).');
      return;
    }
    const sanitized = sanitizePayload(data);
    const payload = sanitized;
    rawGraphData = payload;
    model = buildGraphModel(payload);
    void ensureAiStatus();
    try {
      updateStatsPanel(payload.stats || {});
    } catch (_e) { /* */ }
    const sdd = document.getElementById('stat-dark');
    if (sdd) {
      sdd.textContent = String(payload.nodes.filter((n) => n.type === 'dark_matter').length);
    }
    const sde = document.getElementById('stat-entangled');
    if (sde) {
      sde.textContent = String(payload.links.filter((l) => l.type === 'ENTANGLED').length);
    }
    if (!app) {
      initPixi();
    }
    loadLevelGalaxy();
    if (TIMELINE_API_URL) {
      fetch(TIMELINE_API_URL, { cache: 'no-store' })
        .then((r) => (r.ok ? r.json() : null))
        .then((data) => {
          if (data && data.snapshots && data.snapshots.length > 0) {
            timelineData = data;
            const btn = document.getElementById('btn-timeline');
            if (btn) btn.style.display = '';
            const slider = document.getElementById('timeline-slider');
            if (slider) {
              slider.max = String(data.snapshots.length - 1);
              slider.value = String(data.snapshots.length - 1);
            }
            const td = document.getElementById('timeline-date');
            if (td) td.textContent = data.first_date;
            const te = document.getElementById('timeline-date-end');
            if (te) te.textContent = data.last_date;
          }
        })
        .catch(() => {});
    }
    if (localStorage.getItem(STORAGE_VISITED) === '1') {
      entranceDone = true;
    }
    playEntrance((payload && payload.stats) || {});
  };

  /** Studio: incremental updates (T2+); T1 is no-op */
  studio._ingestDelta = function (_message) { /* T2 */ };

  studio._destroy = function () {
    window.removeEventListener('keydown', __omnixKeydownHandler);
    window.removeEventListener('resize', __omnixResizeHandler);
    if (starfieldTwinkle) {
      try {
        starfieldTwinkle.kill();
      } catch (_e) { /* */ }
    }
    starfieldTwinkle = null;
    try {
      killTweens();
    } catch (_e) { /* */ }
    if (app) {
      try {
        if (studio._mainTicker) {
          app.ticker.remove(studio._mainTicker);
        }
      } catch (_e) { /* */ }
      try {
        app.destroy(true, { children: true, texture: true });
      } catch (_e) { /* */ }
    }
    app = null;
  };
""".lstrip(
        "\n"
    )


if __name__ == "__main__":
    main()
